version: '3'

services:
  database:
    container_name: bs_database
    image: postgres:14.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: bsecret
    volumes:
      - bsecret_db:/var/lib/postgresql

volumes:
  bsecret_db:
